# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import id_mapper_pb2 as id__mapper__pb2


class ID_mapperStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ID_map = channel.unary_unary(
        '/ID_mapper/ID_map',
        request_serializer=id__mapper__pb2.Number.SerializeToString,
        response_deserializer=id__mapper__pb2.Number.FromString,
        )
    self.Get_clients_list = channel.unary_unary(
        '/ID_mapper/Get_clients_list',
        request_serializer=id__mapper__pb2.Number.SerializeToString,
        response_deserializer=id__mapper__pb2.IntList.FromString,
        )


class ID_mapperServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ID_map(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get_clients_list(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ID_mapperServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ID_map': grpc.unary_unary_rpc_method_handler(
          servicer.ID_map,
          request_deserializer=id__mapper__pb2.Number.FromString,
          response_serializer=id__mapper__pb2.Number.SerializeToString,
      ),
      'Get_clients_list': grpc.unary_unary_rpc_method_handler(
          servicer.Get_clients_list,
          request_deserializer=id__mapper__pb2.Number.FromString,
          response_serializer=id__mapper__pb2.IntList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ID_mapper', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
