# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: id_mapper.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='id_mapper.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fid_mapper.proto\"\x07\n\x05\x45mpty\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x05\"#\n\x07IntList\x12\x18\n\x0c\x63lients_list\x18\x04 \x03(\x05\x42\x02\x10\x01\x32R\n\tID_mapper\x12\x1c\n\x06ID_map\x12\x07.Number\x1a\x07.Number\"\x00\x12\'\n\x10Get_clients_list\x12\x07.Number\x1a\x08.IntList\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=26,
)


_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Number.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=51,
)


_INTLIST = _descriptor.Descriptor(
  name='IntList',
  full_name='IntList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clients_list', full_name='IntList.clients_list', index=0,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
DESCRIPTOR.message_types_by_name['IntList'] = _INTLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'id_mapper_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), {
  'DESCRIPTOR' : _NUMBER,
  '__module__' : 'id_mapper_pb2'
  # @@protoc_insertion_point(class_scope:Number)
  })
_sym_db.RegisterMessage(Number)

IntList = _reflection.GeneratedProtocolMessageType('IntList', (_message.Message,), {
  'DESCRIPTOR' : _INTLIST,
  '__module__' : 'id_mapper_pb2'
  # @@protoc_insertion_point(class_scope:IntList)
  })
_sym_db.RegisterMessage(IntList)


_INTLIST.fields_by_name['clients_list']._options = None

_ID_MAPPER = _descriptor.ServiceDescriptor(
  name='ID_mapper',
  full_name='ID_mapper',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=90,
  serialized_end=172,
  methods=[
  _descriptor.MethodDescriptor(
    name='ID_map',
    full_name='ID_mapper.ID_map',
    index=0,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Get_clients_list',
    full_name='ID_mapper.Get_clients_list',
    index=1,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_INTLIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ID_MAPPER)

DESCRIPTOR.services_by_name['ID_mapper'] = _ID_MAPPER

# @@protoc_insertion_point(module_scope)
